### ISSUE TITLE
Typo in production.py

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#45]
I think the following should be `skip = False` instead of `skip = false`

from:
https://github.com/heathsc/gemBS/blob/fca06d59931a6639fee89839009847d84a08824a/gemBS/production.py#L481-L484

At the moment, I get the following error because of this:

```
Traceback (most recent call last):
  File "/home/ucbtmog/.pyenv/versions/3.5.3/bin/gemBS", line 13, in <module>
    load_entry_point('gemBS==3.2.6', 'console_scripts', 'gemBS')()
  File "/home/ucbtmog/.pyenv/versions/3.5.3/lib/python3.5/site-packages/gemBS/commands.py", line 157, in gemBS_main
    instances[args.command].run(args)
  File "/home/ucbtmog/.pyenv/versions/3.5.3/lib/python3.5/site-packages/gemBS/production.py", line 367, in run
    self.do_mapping(fl)
  File "/home/ucbtmog/.pyenv/versions/3.5.3/lib/python3.5/site-packages/gemBS/production.py", line 483, in do_mapping
    skip = false
NameError: name 'false' is not defined
```

**Comment by heathsc** [comment]
Fix applied.
