### ISSUE TITLE
Mapping with singularity gemBS

### ISSUE THREAD

**Issue by DolapoA** [heathsc/gemBS#57]
Whilst mapping I came across a mapping error reminiscent of:  #46 

_2019-08-16 08:36:36,894 ERROR: Process '/usr/local/lib/python3.5/dist-packages/gemBS/gemBSbinaries/gem-mapper' finished with 1
Traceback (most recent call last):
  File "/usr/local/bin/gemBS", line 11, in <module>
    load_entry_point('gemBS==3.3.0', 'console_scripts', 'gemBS')()
  File "/usr/local/lib/python3.5/dist-packages/gemBS/commands.py", line 159, in gemBS_main
    instances[args.command].run(args)
  File "/usr/local/lib/python3.5/dist-packages/gemBS/production.py", line 371, in run
    self.do_mapping(fl)
  File "/usr/local/lib/python3.5/dist-packages/gemBS/production.py", line 564, in do_mapping
    under_conversion=self.underconversion_sequence,over_conversion=self.overconversion_sequence) 
  File "/usr/local/lib/python3.5/dist-packages/gemBS/__init__.py", line 746, in mapping
    raise ValueError("Error while executing the Bisulfite bisulphite-mapping")
ValueError: Error while executing the Bisulfite bisulphite-mapping_

I was wondering whether this version of gemBS was updated as in #46.

**EDIT:** I've seen that in fact I have the latest version of gemBS.

**Comment by DolapoA** [comment]
The problem was caused by an incorrect  path in the samples.csv file.

**Comment by heathsc** [comment]
Thanks for the report

Simon
